# Generated by Django 5.0b1 on 2023-11-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.TextField()),
                ('date', models.DateField()),
                ('blog_content', models.TextField()),
            ],
        ),
    ]
